### PR TITLE
Subcommand breaks StdLib OptionParser tests

### PR DESCRIPTION
**Pull request by jasonkarns**
I noticed some inconsistencies with the way OptionParser was behaving after subcommand was loaded/monkey-patched.

So I pulled down the ruby source so that I could run the optparse stdlib tests after loading subcommand. Results:

```
71 tests, 627 assertions, 18 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
73.2394% passed
```

This PR adds ruby source as a git submodule (shallow checkout; I configured my own for sparse-checkout, but even a full checkout with depth 1 is decently fast). Then it adds a rake task for running the stdlib test suite: `stdlib_test`.

Issues resolved herein:

1. `summarize` was being made private; should be public
2. summary output contained extraneous newlines even without subcommands present
3. `parse!` was returning `nil` when a non-option, non-subcommand argument was encountered. Instead, it should be returning the remaining args, with the thrown argument restored to the array.

Now:
```
71 tests, 701 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```

I realize have the ruby source as a submodule is really weird. Open to suggestions for how to include those tests. Also open to suggestions for how you might like these tests included in the main test task (so they'll always be run, instead of as separate suite). Lastly, FYI: this has only been tested on ruby v 2.4.1. Unsure about backcompat or which versions this should support.

### CODE REVIEW

**Comment by bjeanes** [comment]
Wow @jasonkarns.. good call!

I don't use this submodule on any active projects so don't have any strong preferences. I think Ruby as submodule is a reasonable solution, except that it doesn't have a great story for testing against multiple versions of Ruby.

I wonder if there are any other libraries that do this kind of thing that offers some prior art to follow...

**Comment by jasonkarns** [comment]
I spent a good chunk of time googling last night before I went down the submodule route. There may be something out there, but it's quite a difficult topic to query for.

I'll break the fixes into a separate PR and try to see why the travis builds aren't running.

**Comment by bjeanes** [comment]
Maybe instead of submoduling, we just need a test script which shallow fetches the ruby version under test? A submodule will always be pinned to a particular ref...

> I'll break the fixes into a separate PR and try to see why the travis builds aren't running.

They probably aren't running because it's been literally years :)

**Comment by bjeanes** [comment]
OK Fixed the API token in the Travis hook. It should build now, but it probably won't succeed due to some too old Ruby versions and a bad rake dependency for the not-too-old-but-still-old Ruby versions.

**Comment by jasonkarns** [comment]
Care to keep support for those old ruby versions? We could drop support for them (which will simplify the gemspec and will allow use of latest rake version). Of course, this would necessitate a major version bump. But given that OS X now ships with 2.0, I don't think starting at 2.x support would be leaving too many out in the cold. Or 1.9.3 at the very least.

**Comment by jasonkarns** [comment]
WIP branch for upgrading rspec to 3 https://github.com/jasonkarns/optparse-subcommand/tree/rspec-upgrade
WIP branch for pulling down rubies based on current running ruby: https://github.com/jasonkarns/optparse-subcommand/tree/stdlib-tests-multiple-rubies

(second branch contains the first, so the diff is misleading. better comparison:  https://github.com/jasonkarns/optparse-subcommand/compare/rspec-upgrade...jasonkarns:stdlib-tests-multiple-rubies

**Comment by bjeanes** [comment]
Is the plan here to merge #6 then rebase these fixes on it for a merge or will you open a diff PR?

**Comment by jasonkarns** [comment]
Up to you. #6 needs rebased now that #7 has been merged. But #6 will add failing tests (that this will fix). I think what I might do is change #6 to add the stdlib tests, but not have them triggered by travis? Then this PR can enable the stdlib tests within travis and also ensure they're green all in one go.

Or I can open a new PR that adds the stdlib tests and includes these fixes to ensure they're green all at once. Up to you.

**Comment by jasonkarns** [comment]
Travis is apparently not recognizing the new commits on this branch/PR. (Presumably because this PR was opened back when the travis api token was wrong.)

However, the build of this branch on my fork is green: https://travis-ci.org/jasonkarns/optparse-subcommand/builds/223985486

**Comment by jasonkarns** [comment]
Sorry for all the noise, @bjeanes. Anyway, #6 has been rebased on master and fails _correctly_ because of the stdlib tests. This PR has been rebased onto #6 so it includes both the stdlib tests and the fixes for them. As noted above, the branch for this PR is green on my fork, so it should be safe to merge.

**Comment by jasonkarns** [comment]
closing and reopening PR as suggested by travisci https://github.com/travis-ci/travis-ci/issues/7631#issuecomment-295797041

**Comment by bjeanes** [comment]
🎉 Thanks!

I'll probably release this as v2 due to dropping 1.8.x and the actual stdlib fixes.

**Comment by bjeanes** [comment]
@jasonkarns any other things you were planning to contribute/propose that I should hold off on before a release?

**Comment by jasonkarns** [comment]
I do have a feature I want to add but it's still half-baked. Probably not worth holding off on the release.

**Pull request merged**
